version: "3.1"
services:
  keycloak:
    image: quay.io/keycloak/keycloak:18.0.2
    command:
      - start-dev
      - --import-realm
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    volumes:
      - ./test/:/opt/keycloak/data/import/
  gateway:
    image: kcgateway:dev
    ports:
      - "9080:8080"
    volumes:
      - ./config/application.yml:/opt/config/application.yml
