spring:
  cloud:
    gateway:
      default-filters:
        - TokenRelay
      routes:
        - id: product-resource-server
          uri: http://192.168.6.47:9191
          predicates:
            - Path=/product/**
  security:
    oauth2:
      client:
        provider:
          keycloak-provider:
            issuer-uri: http://192.168.6.47:8080/realms/My-Realm
            # Individual properties can also be provided this way
#            token-uri: http://localhost:8080/auth/realms/amrutrealm/protocol/openid-connect/token
#            authorization-uri: http://localhost:8080/auth/realms/amrutrealm/protocol/openid-connect/auth
#            userinfo-uri: http://localhost:8080/auth/realms/amrutrealm/protocol/openid-connect/userinfo
#            user-name-attribute: preferred_username
        registration:
          spring-gateway-client:
            provider: keycloak-provider
            scope: openid
            client-id: spring-gateway-client
            client-secret: 3RhEF8pqKTANrQ6BhfxaYVmcjTXsDK0u
            authorization-grant-type: authorization_code
            redirect-uri: "http://192.168.6.47:9080/login/oauth2/code/spring-gateway-client"

# Enable these to debug the Authorization flow
logging:
    level:
      org:
        springframework:
          security:
            web: DEBUG
          cloud:
            gateway: DEBUG
server:
  port: 9080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10000/eureka/